#!/bin/bash

help() {
    echo "upgrade ( pre | do | post1 | post2 )"
    exit 0
}

if [ $# == "0" ]; then
    help
fi

USER=$(whoami)
if [ $USER != "root" ]; then
   echo "only root may run this program"
   exit 1
fi

CHOICE="$1"

case "$CHOICE" in
    pre)
        echo "pre: checkupdates"
        checkupdates
        ;;
    do)
        echo "do: pacman -Syu"
        pacman -Syu
        ;;
    post1)
        CMD="grep -F $(date +%F) /var/log/pacman.log"
        echo "post1: $CMD"
        eval $CMD
        ;;
    post2)
        CMD="find /etc -name '*.pacnew' -o -name '*.pacsave'"
        echo "post2: $CMD"
        eval $CMD
        ;;
    *)
        help
        ;;
esac
